# Example api requests

## Media resource

### Get all media
GET http://localhost:3000/api/media

### Get a media item based on id
GET http://localhost:3000/api/media/2
### Get media item FAIL (id not found)
GET http://localhost:3000/api/media/96399

### Create an item
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjE5ODc5NywiZXhwIjoxNzMyMjg1MTk3fQ.kEoqfb4NACXmSJDtZWKcdKUTXlMDZr_UV18n_IQsx-8
Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="title"

New cat image
------Boundary
Content-Disposition: form-data; name="description"

Kiva kuva kissasta.
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./cat2.png
------Boundary--

### Create an item FAIL (title missing)
POST http://localhost:3000/api/media
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjQ2OTEyMCwiZXhwIjoxNzMyNTU1NTIwfQ.gaLPJkQgX4UvJEEFxfPxZAvcMOMs0Zc21-HPyQ572to

Content-Type: multipart/form-data; boundary=----Boundary

------Boundary
Content-Disposition: form-data; name="description"

Kiva kuva kissasta.
------Boundary
Content-Disposition: form-data; name="file"; filename="image.png"
Content-Type: image/png

< ./cat2.png
------Boundary--

### Update an item
PUT http://localhost:3000/api/media/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjQ2OTEyMCwiZXhwIjoxNzMyNTU1NTIwfQ.gaLPJkQgX4UvJEEFxfPxZAvcMOMs0Zc21-HPyQ572to
Content-Type: application/json

{
  "title": "Uusi title kuvalle",
  "description": "Tosi kiva kuva kissasta."
}


### Login 
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "updatdddceduser",
  "password": "cdzcccd_pw1"
}
### get login user info
GET http://localhost:3000/api/auth/login  
Authorization

### Get my user info
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjUyMDM1NywiZXhwIjoxNzMyNjA2NzU3fQ.7NB9qFMbTbd5_7Af-hfGf3_IssKLnM1oQrab3hfilXE
### get
GET http://localhost:3000/api/users/1
Authorization 
### put
PUT http://localhost:3000/api/media/7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjE5ODc5NywiZXhwIjoxNzMyMjg1MTk3fQ.kEoqfb4NACXmSJDtZWKcdKUTXlMDZr_UV18n_IQsx-8
Content-Type: application/json

{
  "title": "OK",
  "description": "nice"
}

### delete
DELETE http://localhost:3000/api/media/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjE5ODc5NywiZXhwIjoxNzMyMjg1MTk3fQ.kEoqfb4NACXmSJDtZWKcdKUTXlMDZr_UV18n_IQsx-8

### Like a media item
POST http://localhost:3000/api/likes/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjUyMDM1NywiZXhwIjoxNzMyNjA2NzU3fQ.7NB9qFMbTbd5_7Af-hfGf3_IssKLnM1oQrab3hfilXE
Content-Type: application/json

{
  "media_id": 1
}
### Like a media item FAIL (already liked)
GET http://localhost:3000/api/likes/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjUyMDM1NywiZXhwIjoxNzMyNjA2NzU3fQ.7NB9qFMbTbd5_7Af-hfGf3_IssKLnM1oQrab3hfilXE


### Unlike a media item
DELETE http://localhost:3000/api/likes/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjIwNDU3NSwiZXhwIjoxNzMyMjkwOTc1fQ._954b_jEmZPi7KaG0XXuS22ubsbYJNBIv5aBiy3HfC0

### delete media
DELETE http://localhost:3000/api/media/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjIwNDU3NSwiZXhwIjoxNzMyMjkwOTc1fQ._954b_jEmZPi7KaG0XXuS22ubsbYJNBIv5aBiy3HfC0

### delete media

DELETE http://localhost:3000/api/media/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VybmFtZSI6InVwZGF0ZWR1c2VyIiwicGFzc3dvcmQiOiJoYXNoZWRfcHcxIiwiZW1haWwiOiJ1cGRhdGVkQGV4YW1wbGUuY29tIiwidXNlcl9sZXZlbF9pZCI6MiwiY3JlYXRlZF9hdCI6IjIwMjQtMTEtMTZUMDY6NDg6MDcuMDAwWiIsImlhdCI6MTczMjIwNDU3NSwiZXhwIjoxNzMyMjkwOTc1fQ._954b_jEmZPi7KaG0XXuS22ubsbYJNBIv5aBiy3HfC0

### post user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "Nihadd",
  "email": "testudwdser@example.com",
  "password": "rdsdadas123"
}

### post user
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "essefil",
  "email": "Aleesifl@example.com",
  "password": "faewiss123"
}
### post email
POST http://localhost:3000/api/auth/forgotpassword
Content-Type: application/json

{
  "email": "Aleeifl@example.com"
}
